version: '3.5'
services:
  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      stargate: null
    volumes:
      - "./selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"

    command: [ "-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid-dev", "-limit", "10" ]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    links:
      - selenoid
    networks:
      - stargate
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  tests:
    build: .
    depends_on:
      - selenoid
      - selenoid-ui
    container_name: run-tests
    command: sh -c "cd /app && gradle clean test"
    networks:
      - stargate

networks:
  default:
  stargate:
    name: selenoid-dev
    driver: bridge